### PR TITLE
Fix typo in rabbitmq-env.sh affecting TLS

### LINKED ISSUE #159: Typo in rabbitmq-env.sh
Hi. 
You have a typo in bitnami-docker-rabbitmq/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh on the right side of your expression:
export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_SSL_KEYFILE:-/tmp/rabbitmq_combined_keys.pem}"
There should be an:
export RABBITMQ_COMBINED_CERT_PATH="${RABBITMQ_COMBINED_CERT_PATH:-/tmp/rabbitmq_combined_keys.pem}"

### PR DESCRIPTION
**Pull request by gaby**
Fix for small typo in ENV variables used for TLS. It seems this typo is affecting the ability of using TLS with this image.

Closes #159

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]
Thank you for the PR! LGTM

**Review by javsalgar — COMMENTED** [review]
I've checked with the team and it seems that this value is intentional. I'm pinging @rafariossaa as the author of this

**Comment by gaby** [comment]
@javsalgar Any updates on this ?

**Comment by rafariossaa** [comment]
Hi @gaby, 
  Sorry for the delay, I am checking this.

**Comment by rafariossaa** [comment]
Hi,
  This is related to https://github.com/bitnami/bitnami-docker-rabbitmq/pull/152 , Could you take a look to it ?
  Also, I am not very sure how is this affecting the TLS usage. Could you elaborate a bit more on this issue ?

**Comment by gaby** [comment]
I'm not really sure if it's affecting TLS, but I could never get TLS working with this image. We ended up going back to the one from docker-library.

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate what have you tried so far? Maybe I can help you to configure it.

**Comment by gaby** [comment]
@rafariossaa See #164

**Comment by rafariossaa** [comment]
When trying to reproduce this error, I hit that issue too when following the rabbitmq [instructions for TLS](https://www.rabbitmq.com/ssl.html) and using `tls-gen` :
` Invalid certificate file /opt/tls/key.pem: decoding error`
The issue is that the key pem file needs to start with:
`-----BEGIN RSA PRIVATE KEY-----` 
So I decided to generate the certs with openssl instead. 
Could you give it a try ?

**Pull request closed without merging**
