### PR TITLE
Introduce flag files to mark complete initialization

### PR DESCRIPTION
**Pull request by horazont**
**Description of the change**

The data directory is now marked with two different files depending on the phase of initialization:

- If the directory is empty, it is marked with an "init" file to note that initialization needs to happen.
- If the directory is non-empty and marked with an "init" file, but no "complete" file, re-try the initialization procedure.
- If the directory is non-empty and contains the "complete" marker, proceed with normal startup.
- If the directory is non-empty, but no marker file is present, we assume that this is an upgrade with an existing, healthy cluster and mark the initialization as complete by placing both markers.

**Benefits**

If the container fails to initialize the RabbitMQ cluster on the first attempt, because of a bug in the scripts, because of timeouts or because it gets killed while doing something, it will now re-try the initialization instead of assuming everything is fine. This makes initialization much more robust.

**Possible drawbacks**

As far as I can tell, all initialization is (assuming that no other data has been written yet) idempotent. The flag files prevent re-initialization when data is already present. Hence, I think that this change has no drawbacks.

**Applicable issues**

Without this change, it is possible that the first attempt at initializing RabbitMQ fails spuriously (for example, due to a timeout while starting the RabbitMQ service in background because the cluster is overloaded).

In that case, the data directory may still be non-empty afterward, causing the subsequent run of the container to assume that configuration has completed. If this is used with the secure way of setting the user password, it will cause the user to not be configured at all, making subsequent attempts to interact with the cluster fail.

(I filed no issue because I created a fix right away.)

**Additional information**

- If you don’t like the approach, I’m open to discussing others.
- Change is also fully described in the commit message for future code archeology.
- We saw the described issue (RabbitMQ failing to start in background during initial setup) at least twice in our CI pipeline where we start a handful of RabbitMQ clusters using the Bitnami chart, so it is a definite issue.

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi @horazont,
Thank you very much for this PR!
I think there were more users interested on this feature in other containers, so we should use a standard approach for all of them .By the moment I will set this on-hold and will rise the priority of our internal task to achieve this.

**Comment by miguelaeh** [comment]
Related issue: https://github.com/bitnami/bitnami-docker-rabbitmq/pull/153

**Comment by horazont** [comment]
@miguelaeh 
Hi and thanks for the quick reply!

I don’t think #153 is exactly the same (I saw that PR and judged it was not) or even quite related, so I’m not sure if I was understood correctly. Can you show me examples where people have asked for something similar?

I just want to make sure that we’re on the same page and that I’ve expressed myself clearly.

**Comment by miguelaeh** [comment]
Hi @horazont ,
From what I understood, you are requesting to add some login that will retry the initialization based on some files that act as flags to mark initialization phases.
The issue I shared is requesting to add files as flags to know when the initialization finishes. So I think they are, maybe not exactly the same, but related.
Isn't that what you are requesting? Did I understand it in a bad way?

**Comment by horazont** [comment]
Yes, in that sense they’re related.

The important bit for me is the outcome of "there is always a correctly provisioned user, or the container does not run", not the status flag.

**Comment by miguelaeh** [comment]
Hi @horazont ,
I discussed your proposed changes with the team, and for the moment we decided that that kind of logic will not be supported in the short term. When the initialization fails you will need to manually recover it. This is because we have to be really careful with user's data, we should not be touching the persisted volumes once they have been mounted.

**Comment by horazont** [comment]
Hi @miguelaeh 

Thanks for the reply. I fully understand that stance and I can see where you’re coming from and I support it.

With that in mind, we were discussing on our end how we could approach the issue differently. We have a few things in mind and may propose a different solution to our issue (timeouts causing RabbitMQ to come up unusable in automated scenarios) either here or in the helm charts!

Thanks!

**Pull request closed without merging**
